version: "0.2"
language: en-US
ignorePaths:
  - "dist/**"
  - "node_modules/**"
  - "pnpm-lock.yaml"
  - "public/vendored/**"
words:
  - Baki
  - Codeberg
  - esbuild
  - frontmatter
  - GOARCH
  - gengo
  - inkscape
  - invertocat
  - Mersenne
  - neofetch
  - Onefetch
  - println
  - Qilin
  - RGBA
  - Signalis
  - spenserblack
  - steamdown
