/**
 * @module nicknames
 * The adjectives and nouns are inspired by the 108 heroes of the book Water Margin.
 */
import { createPick } from "./chance";

const prefixes: string[] = [
  "Divine",
  "Daylight",
  "The",
  "Iron",
  "Demon",
  "Small",
  "Leaping",
  "Fiery Eyed",
  "Arrow Struck",
  "Two Spears",
  "Sky",
  "Golden Haired",
  "Cloud",
  "Flowery Necked",
  "Great",
  "Ever Victorious",
  "Nimble",
  "Purple Bearded",
  "Two Bludgeons",
  "Marvelous",
  "Disliked",
  "Jade Armed",
  "Fiery",
  "Restless",
  "Winged",
  "Flying",
  "Muddy",
  "Hell's",
  "Striking",
  "Tiger Fighting",
  "Roaring",
  "Red Haired",
  "Little",
  "Tattooed",
  "Jade",
  "Iron Flute",
  "Jade",
  "Slightly Restrained",
  "Unrestrained",
  "Golden Winged",
  "Iron Faced",
  "Heavenly Eyes",
  "Living",
  "Water",
  "Golden Eyed",
  "Stone",
  "Welcome",
  "Night",
  "Urgent",
  "Nine Tailed",
  "River Churning",
  "Cave",
  "Lightning",
  "Fire God",
  "Clever",
  "Eight Arms",
  "Sacred Handed",
  "Double Tailed",
  "Double Headed",
  "Disgraced",
  "Sick",
  "White Speckled",
  "Glorious",
  "Elegant",
  "Blue Faced",
  "Dangerous",
  "Market",
  "Laughing",
  "Dry Land",
  "Intuitive",
  "Forest",
  "Heavenly",
  "Stinging",
  "Door",
  "Green Grass",
  "Grand",
  "Hairless",
  "Elder",
  "Devil Acting as",
  "Great",
  "Old",
];

const names: string[] = [
  "Doctor",
  "Rat",
  "God",
  "Flower",
  "Arm",
  "Carver",
  "Whirlwind",
  "Tiger",
  "Traveler",
  "Beast",
  "General",
  "Dog",
  "King",
  "Dragon",
  "Tigress",
  "Halberd",
  "Suppressor",
  "Mathematician",
  "One",
  "Craftsman",
  "Star",
  "Ox",
  "Judge",
  "Hawk",
  "Thunder",
  "Demon",
  "Marquis",
  "Monk",
  "Qilin",
  "Immortal",
  "Clerk",
  "Thunderer",
  "Flea",
  "Rain",
  "Fan",
  "Diamond",
  "Witch",
  "Vanguard",
  "Leopard",
  "Tortoise",
  "Clam",
  "Goddess",
  "Calligrapher",
  "Scorpion",
  "Snake",
  "Expert",
  "Prodigy",
  "Brute",
  "Road Spirit",
  "Flute",
  "Arrow",
  "Gardener",
  "Fish",
  "Squire",
  "Tyrant",
  "Crocodile",
  "Lord",
  "Strategist",
  "Marshal",
  "Wasp",
  "Secretary",
  "Ogre",
  "Scholar",
  "Watchman",
  "Sword",
];

const suffixes: string[] = [
  "of Three Mountains",
  "of Death",
  "of Disorder",
  "on the Drum",
  "Who Stands Their Ground",
  "in the Clouds",
  "Without Feathers",
  "of the Beautiful Whiskers",
  "of Heaven",
  "of the Imperial Guard",
  "Who Crosses the Road",
  "of the Western Pass",
];

export const prefix: () => string = createPick(prefixes);
export const name: () => string = createPick(names);
export const suffix: () => string = createPick(suffixes);
